apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: aws-anthropic
  namespace: kagent
spec:
  provider: Bedrock
  model: us.meta.llama3-1-8b-instruct-v1:0
  apiKeySecret: bedrock-credentials
  bedrock:
    region: us-east-1
