apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: crossplane-agent-model-config
  namespace: kagent
spec:
  model: MiniMaxAI/MiniMax-M2.5d
  provider: OpenAI
  apiKeySecret: vultr-inference
  apiKeySecretKey: OPENAI_API_KEY
  openAI:
    baseUrl: https://api.vultrinference.com/v1
